//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmProject.Enity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FilmDBEntities : DbContext
    {
        public FilmDBEntities()
            : base("name=FilmDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TFilm> TFilm { get; set; }
        public virtual DbSet<TOyuncu> TOyuncu { get; set; }
        public virtual DbSet<TKategori> TKategori { get; set; }
    }
}
