//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmProject.Enity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOyuncu
    {
        public int ID { get; set; }
        public string Oyuncu { get; set; }
        public Nullable<int> Film { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual TFilm TFilm { get; set; }
    }
}
